### ISSUE TITLE
Realtime synchronization with a live data proxy not persisting to db

### ISSUE THREAD

**Issue by clibu** [appy-one/acebase#22]
I've written code based on https://github.com/appy-one/acebase#realtime-synchronization-with-a-live-data-proxy and have traced through the AceBase code in ``data-proxy.ts`` and can see the underlying object get changed in ```set(target, prop, value, receiver)``` however nothing is written to the database and there are no errors. 

```set()``` calls ```context.flag('write', context.target.concat(prop));``` which calls ``scheduleSync()`` but db isn't updated. 

The specific property is a string assignment.

This is using IndexedDb in the Browser.

**Comment by clibu** [comment]
A bit more info. Sometimes the data persists. I can't see a pattern. Maybe timing related. I've also see an empty IndexedDB record. ie. ``value`` is ``{}`` instead of ``{ someKey: "someValue" }``

**Comment by appy-one** [comment]
Can you tell me a bit more about your setup? Are you using an AceBase instance with IndexedDB storage in combination with an AceBaseClient that syncs to a server, or just the IndexedDB as standalone db? Also, let me know which versions of the acebase packages you are using

**Comment by clibu** [comment]
AceBase standalone with IndexedDB in the Browser.  acebase": "^1.1.4 

I'll update to the latest version.

**Comment by clibu** [comment]
Updated to "acebase": "^1.2.3", - Same problem.

**Comment by clibu** [comment]
I don't know if it is relevant but the path is just one node. ie "clibu_app" vs "clibu_app/blah"

**Comment by appy-one** [comment]
Thanks, I'll try to reproduce

**Comment by appy-one** [comment]
I've tested a couple of things but can't reproduce. See code below
```js
const db = AceBase.WithIndexedDB('debug');
db.ready(async () => {
        const ref = db.ref('test');
        const proxy = await ref.proxy({});
        const obj = proxy.value;
        obj.string = 'Testing ' + Math.random();
        setTimeout(async () => {
          // Running with delay to make sure value was written
          const snap = await ref.get();
          const val = snap.val();
          console.assert(obj.string === val.string, 'wrong string'); // Ok
        }, 1000);
});
```

**Comment by clibu** [comment]
Same problem with your sample code. ```TypeError: Cannot read property 'string' of null``` in the ```assert()``` call. And nothing in the IndexedDB table. 

I'll dig deeper into the code and see what I can find.

FYI it is 6:50am now here in Australia. A new day starts.

**Comment by appy-one** [comment]
Goodmorning early bird! 21:30 pm here in The Netherlands. 😊
Can you check the version of acebase-core in your node_modules. The latest version is 1.2.3.
You might want to ```npm uninstall acebase``` and ```npm install acebase``` to make sure the latest acebase-core is installed. I've fixed quite a few proxy issues, which is in the core package.

**Comment by clibu** [comment]
FWIW I'm using yarn. I did a ``yarn remove acebase`` yesterday and ``yarn add acebase``

package.json for acebase-core is "version": "1.2.3"

For you sample code when it fails I just see:
````
[debug] Read node "/" and (filtered) descendants from 1 records
storage-custom.js:671 
[debug] Node "/" is being updated
````
twice.

When it works ok I also see:
````
[debug] Read node "/test" and descendants from 1 records
````

I'm starting to suspect some interference from other IndexedDB libs I'm using maybe causing this. More in next post.

**Comment by clibu** [comment]
I'm using [nanoSQL ](https://nanosql.io/) as the main db lib at present and [Logux.io](https://logux.io/) for Server Sync which also uses IndexedDB. I've been using both of these for quite some time without any issues. I'm looking at using AceBase either as well as nanoSQL or possibly to replace it.

I've isolated nanoSQL and Logux so I only use AceBase proxy and am still seeing the same issue. I haven't noticed any issues using AceBase ```db.ref( path ).update( doc )```

I'm not sure what to try next. I can tell you that if I step through a proxy update in the Chrome Debugger then it is more likely to work ok.

**Comment by clibu** [comment]
Some more info. I'm toggling the value ``displayNotesInGrid`` between true and false of and seeing the following.
````
[ClibuAppAB] Node "/clibu_app" is being updated
storage-custom.js:818 [ClibuAppAB] Node "/clibu_app/displayNotesInGrid" is being deleted
storage-custom.js:840 [ClibuAppAB] Nodes "/clibu_app/displayNotesInGrid" are being deleted
````

The `` target[prop] = value;`` at line 937 in data-proxy.ts is correct. However  "/clibu_app/displayNotesInGrid" is not present in IndexedDB.

**Comment by appy-one** [comment]
Have you tried removing/clearing the db for a fresh start? Do you get the same results?

**Comment by clibu** [comment]
Yes many times. Helps for a bit then the issues reappear.
I've now just seen:
```key: "", value: {clibu_app: {…}}```
which is really odd as clibu_app is never used as property value.

**Comment by appy-one** [comment]
This is really hard without being able to reproduce. Are you using multiple proxies at the same time, other code that monitors values, or code that might change values in the db at the same time?

**Comment by appy-one** [comment]
Can you set logLevel to 'verbose': ```const db = AceBase.WithIndexedDB('debug', { logLevel: 'verbose' });```, run the test code from above and copy/paste the console output?

**Comment by clibu** [comment]
There is another Proxy on the same DB but only the one with your sample code. I'll remove all of my AceBase code and just use your sample with verbose - after I've had some breakfast.😀

**Comment by appy-one** [comment]
Enjoy your breakfast. I might be sleeping when you come back 😂

**Comment by clibu** [comment]
Sleep well.😀 I'll keep trying to narrow this down. 
I've removed all of my AceBase code and now just have you sample. I delete the db and refresh the Browser. Sometimes it works other times the assert raises an exception as per my earlier post.

This is the verbose output from a crash.
````
[debug] Database "debug" details:
storage-custom.js:333 [debug] - Type: CustomStorage
storage-custom.js:334 [debug] - Path: .
storage-custom.js:335 [debug] - Max inline value size: 50
storage-custom.js:336 [debug] - Autoremove undefined props: false
storage-custom.js:776 [debug] Node "/" is being created
storage-custom.js:1095 [debug] Read node "/" and (filtered) descendants from 1 records
storage-custom.js:671 [debug] Node "/" is being updated
storage-custom.js:1095 [debug] Read node "/" and (filtered) descendants from 1 records
storage-custom.js:671 [debug] Node "/" is being updated
````

I think I'll create a new app with just your code.

**Comment by clibu** [comment]
Ok I created the attached Node app and am seeing the same issue.
AceBase V1.2.3 Node v15.11.0 Windows 10 Home Version	10.0.19042 Build 19042 Dell XPS 15

````
[debug] Database "debug" details:
[debug] - Type: AceBase binary
[debug] - Record size: 128
[debug] - Page size: 1024
[debug] - Max inline value size: 50
[debug] - Root record address: 0, 0
[debug] KIT read, 0 keys indexed
[debug] FST read, 0 pages allocated, 0 free ranges
[debug] Node "/" is being created
[debug] Allocated 1 addresses for node "/": 0,0+0
[debug] Node "/" saved at address 0,0 - 1 addresses, 4 bytes written in 1 chunk(s)
[debug] Node "/" is being created
[debug] Allocated 1 addresses for node "/": 0,1+0
[debug] Node "/" saved at address 0,1 - 1 addresses, 8 bytes written in 1 chunk(s)
[debug] Root record address updated to 0, 1
[debug] Node "/test" is being overwritten
[debug] Allocated 1 addresses for node "/test": 0,2+0
[debug] Node "/test" saved at address 0,2 - 1 addresses, 4 bytes written in 1 chunk(s)
[debug] Node "/" being updated: adding 0 keys (), updating 1 keys ("test"), removing 0 keys ()
[debug] Node "/" saved at address 0,1 - 1 addresses, 14 bytes written in 1 chunk(s)
[debug] Reading node "/test" from address 0,2
Assertion failed: wrong string
val: {}
````

I delete the ``debug.acebase`` folder and ``> node proxy1.js`` and get the same error every time. If I don't delete the folder and run it a second time it works as expected.

I also ran just your sample code in the Browser and as before - worked sometimes.

I hope you can reproduce it with the attached files.

[proxy1.zip](https://github.com/appy-one/acebase/files/6160417/proxy1.zip)

**Comment by clibu** [comment]
More info. I've rebooted my XPS15 and same problem. I also tried it on another Win10 Desktop PC - same problem.

**Comment by appy-one** [comment]
Thanks! 👍🏼 I'll dive into it after I've taken the kids to school

**Comment by appy-one** [comment]
Looks like I found the issue 🥳

**Comment by clibu** [comment]
👍 I hope you were able to reproduce it.

**Comment by appy-one** [comment]
Yes! I've made a couple of changes, will publish after some more testing

**Comment by appy-one** [comment]
I published my changes in acebase-core v1.2.4, let me know if this fixes it!

**Comment by clibu** [comment]
Look forward to trying it.
Were you able to reproduce the issue?

**Comment by appy-one** [comment]
I was able to reproduce the failing assert upon creation of the record, not on updates thereafter. BUT, there were a couple things that could have caused that:
1) the context (```ref.context({ acebase_proxy: {...} })```) used to update the database was not set for setting the default value, causing the proxy to think the value was updated from an external source
2) the ```DataReference``` used by the proxy was the same instance as the one used to create the proxy, causing the context set by the proxy to also be used by other code performing update operations on that same ```DataReference``` - causing the proxy to think the update was done by itself, not updating its cached value.
3) If the proxy target value itself was updated, the ```cache``` object reference was updated inside the proxy code, but the external code using the proxy was still poking in the old referenced ```cache``` object.

**Comment by clibu** [comment]
Ok, looking much, much better.  I am seeing one weird thing, but it might be my code. I'll look into it in the morning,

Thanks for looking at this so quickly.

**Comment by clibu** [comment]
This seems a little odd, I just want to check with you.

I've got a path named: "'clibu_app'" which is Proxied. When I start the app, and "'clibu_app'" has no IndexedDB record and I don't assign any key/value to it I'm seeing ```key: "", value:  "{clibu_app: { clibu_app } }"```. Expanding this in Chrome DevTools shows "No properties".

As soon as I assign a value everything looks as I would expect. ``key: "". value: {}`` and a new record ``key: "clibu_app", value: {someObject}``

Other than that all seem ok so far. But I haven't had breakfast yet.😉

**Comment by appy-one** [comment]
Yes, that is by design. I would guess you create the proxy using default value ```{}``` like so ```db.ref('clibu_app').proxy({})```? This will create the path "clibu_app" with value ```{}``` if it doesn't exist. Because it's an empty object (has no children), it is stored in the parent record. Once you assign properties to the "clibu_app" node, it will be stored in its own dedicated record.

**Comment by clibu** [comment]
Thanks and understood. It just looked a little odd. Hopefully full steam ahead now. I have other questions and suggestions, but will leave those until I get further into using AceBase.

**Comment by appy-one** [comment]
You're welcome, Closing this one!
